### ISSUE TITLE
null arguments

### ISSUE THREAD

**Issue by MIvanIsten** [phpseclib/bcmath_compat#2]
The functions are not handling `null` arguments the same way as the php extension.
Argument validation raises warnings for `null` arguments and returns incorrect `null` value as function result.

    print_r(
        array(
            'bcadd(1, 1)' => bcadd(1, 1),
            'bcadd(null, 1)' => bcadd(null, 1),
            'bcadd(1, null)' => bcadd(1, null),
        )
    );

Result with php bcmath:

    Array
    (
        [bcadd(1, 1)] => 2
        [bcadd(null, 1)] => 1
        [bcadd(1, null)] => 1
    )

Result with  phpseclib/bcmath_compat:

    Warning: bcadd() expects parameter 0 to be integer, NULL given in vendor\phpseclib\bcmath_compat\src\BCMath.php on line 418
    
    Warning: bcadd() expects parameter 1 to be integer, NULL given in vendor\phpseclib\bcmath_compat\src\BCMath.php on line 418

    Array
    (
        [bcadd(1, 1)] => 2
        [bcadd(null, 1)] =>
        [bcadd(1, null)] =>
    )

Argument validation should accept `null`.
Since before method calling non numeric arguments are casted to `0`, it is safe to accept `null` at argument validation.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/bcmath_compat/commit/f0362e41e5fbee0d98c7f8539ff82b996d05b09c should fix this! In the commit immediately preceding that one I added a unit test as well.

Thanks!
