### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ollyollyollyltd** [phpseclib/bcmath_compat#5]
Are there any plans to push a new release to Packagist? The current release `2.0.1` is four years old and is throwing deprecation errors in PHP 8.2.

The problem line is https://github.com/phpseclib/bcmath_compat/blob/29bbf07a7039ff65ce7daa44502ba34baf1512ec/src/BCMath.php#L486C1-L486C77 - `2.0.1` makes a deprecated call to `self::class`.

This appears to have been fixed on all three branches, but nothing has been released.

**Comment by terrafrost** [comment]
I'll try to do that in the next few days, latest, this weekend.

Thanks!

**Comment by ollyollyollyltd** [comment]
You're a star, thank you!

**Comment by terrafrost** [comment]
1.0.8 / 2.0.2 have been released.

Thanks!
